### PR TITLE
Jirhiker patch 4

### PR DESCRIPTION
**Pull request by jirhiker**

### CODE REVIEW

**Comment by chrisrycx** [comment]
This is still failing for me when an endpoint raises an error... Are you seeing the same thing?

**Comment by jirhiker** [comment]
Sorry. I haven't been testing, just some blind editing.  Ill do a little more investigation.

Did you try updating fastapi, sqlachemy versions?

What about using multiple uvicorn workers? maybe that way even if the connection pool on one worker fails another worker will take over

**Comment by chrisrycx** [comment]
My versions of fastAPI and sqlalchemy are in the range specified in requirements.txt, but I don't know if they are the max versions. It could be worth upgrading to sqlalchemy 2.0... might not require too many changes.

I haven't messed with uvicorn settings, but I don't see the problem when running locally with basis uvicorn setup.

**Comment by chrisrycx** [comment]
Fixed via another method

**Pull request closed without merging**
